#!/bin/bash

help()
{
cat<<EOT

Arguments:
 -l			lowercase
 -u			uprpercase
 -r			recursive
 -h 			help
 <sed pattern> 		using sed pattern

Examples:
	$name [-r] [-l|-u] <dir|file names>
	$name [-r] <sed pattern> <dir/file names> 


EOT
exit
}


if [ -z "$1" ]
then
		echo "no arguments"
exit

elif [ $1 = "-h" ]
then
	if [[ $2 = "-l" || $2 = "-u" || $2 = "-r" || $2 = "-h" ]]
	then
		echo "invalid syntax"
	exit
	fi
        help


elif [ $1 = "-r" ]
then
	if [[ $2 = "-l" && ! -z "$3" ]]
	then
	for SRC in `find "${@:3}" -depth`
	do
    		DST=`dirname "${SRC}"`/`basename "${SRC}" | tr '[A-Z]' '[a-z]'`
    		if [ "${SRC}" != "${DST}" ]
    		then
        	[ ! -e "${DST}" ] && mv -T "${SRC}" "${DST}" || echo "${SRC} was not renamed"
    	fi
	done

	elif [[  $2 = "-u" && ! -z "$3" ]]
        then
        for SRC in `find "${@:3}" -depth`
	do
    		DST=`dirname "${SRC}"`/`basename "${SRC}" | tr '[a-z]' '[A-Z]'`
    		if [ "${SRC}" != "${DST}" ]
    		then
        	[ ! -e "${DST}" ] && mv -T "${SRC}" "${DST}" || echo "${SRC} was not renamed"
    	fi
	done
	        else
                	for SRC in `find "${@:3}" -depth`
        		do             		
					BASE=`basename "${SRC}"`              			
					DST=`echo "$BASE" | sed -s "$2"`
					DST=`dirname "${SRC}"`/"$DST"
					#echo $DST
					if [ "${SRC}" != "${DST}" ]
                			then
                				[ ! -e "${DST}" ] && mv "${SRC}" "${DST}"
        				fi       			
        		done

		fi





elif [[ $1 = "-l" && ! -z "$2" ]]
then
	if [[ $2 = "-l" || $2 = "-u" || $2 = "-r" || $2 = "-h" ]]
	then
		echo "invalid syntax"
	exit
	fi
        rename 'y/A-Z/a-z/' "${@:2}"
	

elif [[ $1 = "-u" && ! -z "$2" ]]
then
	if [[ $2 = "-l" || $2 = "-u" || $2 = "-r" || $2 = "-h" ]]
	then
		echo "invalid syntax"
	exit
	fi
        rename 'y/a-z/A-Z/' "${@:2}"
else
 	for var in "${@:2}"
do
	mv "$var" "`echo "$var" | sed -s "$1"`"	
done

fi

